apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: ctse
  name: ctse
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ctse
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ctse
    spec:
      containers:
      - image: it19123882/it19123882_ctse_assessment3:760f1da8f7b15c10d27b330d233f59cd969875fc
        imagePullPolicy: Always
        name: it19123882-ctse-assessment3-r9fjt
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 3000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30