apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order_service
  name: order_service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: order_service
status:
  loadBalancer: {}